server:
  tomcat:
    uri-encoding: UTF-8
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kitty?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123456
# mapper xml 文件地址
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
